### ISSUE TITLE
Error when using require in node.js 

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee-js#109]
When trying to use require in node.js (as in the README):
```js
var Bee = require("@ethersphere/bee-js");
```

The following error happens:

```
internal/modules/cjs/loader.js:1174
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/attila/Projects/bee-js-test/index.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by nugaon** [comment]
Babel changed to use [default export in the original way](https://github.com/babel/babel/issues/2212) from version 6.

I suggest to simply remove this feature because of this.
