### ISSUE TITLE
TextEncoder is not defined when running as a dependency in node

### ISSUE THREAD

**Issue by significance** [ethersphere/bee-js#170]
Steps to reproduce.

Install bee-js as a dependency in a node project.

Run the following code.

```
let Bee = require('@ethersphere/bee-js');
let bee = new Bee.Bee('http://localhost:1633');

let topic = '0x0000000000000000000000000000000000000000000000000000000000000001';

let pk = '...';
let ad = '...';

let set = async (payload) => {
	let w = bee.makeFeedWriter('sequence', topic, pk);
	let ref = await bee.createFeedManifest('sequence', topic, ad);
	let r2 = await bee.uploadData(payload);
	let r3 = await w.upload(r2);
}

let get = async (payload) => {
	let r = bee.makeFeedReader('sequence', topic, ad);
	let d = await r.download();
	let p = await bee.downloadData(d.reference);
	console.log("want", payload, "got", p)
	return td.decode(p) === td.decode(payload);
}

let payload = new Uint8Array([i]);
set(payload);
```

fwiw this is how i have previously dealt with the problem that TextEncoder is in the browser context, but must be included from the node module `util`, surely there's a better way :)

```
if (typeof window === "undefined") {
  var TextEncoder = require('util').TextEncoder;
  var TextDecoder = require('util').TextDecoder;  
}else{
  var TextEncoder = window.TextEncoder;
  var TextDecoder = window.TextDecoder;
}
```

**Comment by agazso** [comment]
Hmm, this is interesting because `TextEncoder` is used in bee-js and there are tests running for Node v10, v12 and v14 without issues.

Which node version are you using?
Can you please also provide the actual error you get?

**Comment by significance** [comment]
indeed, unsure why

```
ReferenceError: TextEncoder is not defined
      at prepareData (/Users/sig/Code/swarm2/bee-js-feeds/dist/webpack:/BeeJs/src/utils/data.ts:6:5)
      at Object.upload (/Users/sig/Code/swarm2/bee-js-feeds/dist/webpack:/BeeJs/src/modules/bytes.ts:22:17)
      at t.Bee.uploadData (/Users/sig/Code/swarm2/bee-js-feeds/dist/webpack:/BeeJs/src/bee.ts:52:18)
      at /Users/sig/Code/swarm2/fds.js.bee-js-feeds/dist/ES5/FDS-SwarmFeeds.js:161:33
      at Generator.next (<anonymous>)
      at asyncGeneratorStep (dist/ES5/FDS-SwarmFeeds.js:22:103)
      at _next (dist/ES5/FDS-SwarmFeeds.js:24:194)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by significance** [comment]
it did also happen with direct include from npm

**Comment by vojtechsimetka** [comment]
This also triggers the issue but I can not replicate myself:

```
let Bee = require('@ethersphere/bee-js');
let bee = new Bee.Bee('http://localhost:1633');

async function test(payload) {
    try {
        let ref = await bee.uploadFile(payload);
        let res = await bee.downloadFile(ref);
        console.log(res)
    } catch (e) {
        console.error(e)
    }
}

test('string')
```

**Comment by agazso** [comment]
One clue I found when looking at the [documentation of Node.js](https://nodejs.org/docs/latest-v11.x/api/util.html#util_class_util_textencoder), starting from v11 it states that:
> The TextEncoder class is also available on the global object.

This sentence is missing from the [v10 documentation](https://nodejs.org/docs/latest-v10.x/api/util.html#util_class_util_textencoder).

@significance Is it possible that you are using node v10? If yes can you please verify if the problem still persist if you try it in a newer version?

**Comment by significance** [comment]
ah, yes, this makes sense, I will check

still strange that your node v10 tests work though!

**Comment by vojtechsimetka** [comment]
It might be somehow poly-filled in webpack or the test environment. Once you validate, I see two actions/proposals here:

- ensure the tests for v10 are failing so that we can catch something like this in future
- mark nodejs v10 as not supported, it is anyways nearing end of it maintenance support (two more months) https://nodejs.org/en/about/releases/

**Comment by significance** [comment]
@agazso @vojtechsimetka confirmed, i've updated my proj to node 12 👍

**Comment by AuHau** [comment]
@agazso @vojtechsimetka what do you think is the action here? Should we pronounce v10 "dead"?

**Comment by vojtechsimetka** [comment]
Yes but I really want to understand why it does not fail in our tests because that means we have some issue there.

**Comment by AuHau** [comment]
@vojtechsimetka heh, so the issue seems to be that all the tests run (I guess) on NodeJS v14 😅

https://github.com/ethersphere/bee-js/pull/220/checks?check_run_id=2149222270#step:10:17
