### ISSUE TITLE
flaky test: balance check

### ISSUE THREAD

**Issue by nugaon** [ethersphere/bee-js#302]
There are some cases, when the I got errors on test runs in `integration/modules/debug/balance.spec.ts`

It obviously happens when this test suite runs among of the firsts and there are no balances between nodes yet.

 Exact error message:

```
 FAIL  integration/modules/debug/balance.spec.ts
  ● balance › balances › Get the balances with all known peers including prepaid services

    expect(received).toEqual(expected) // deep equality

    Expected: ArrayContaining [ObjectContaining {"balance": Any<BigInt>, "peer": Any<String>}]
    Received: []

      16 |       const response = await balance.getAllBalances(beeDebugUrl())
      17 |
    > 18 |       expect(response.balances).toEqual(
         |                                 ^
      19 |         expect.arrayContaining([
      20 |           expect.objectContaining({
      21 |             peer: expect.any(String),

      at Object.<anonymous> (test/integration/modules/debug/balance.spec.ts:18:33)

  ● balance › balances › Get the balances with all known peers including prepaid services

    Not Found

      104 |   } catch (e) {
      105 |     if (e.response) {
    > 106 |       throw new BeeResponseError(e.response.status, e.response.statusText)
          |             ^
      107 |     } else if (e.request) {
      108 |       throw new BeeRequestError(e.message)
      109 |     } else {

      at safeAxios (src/utils/safeAxios.ts:106:13)
      at Object.getPeerBalance (src/modules/debug/balance.ts:29:20)
      at Object.<anonymous> (test/integration/modules/debug/balance.spec.ts:34:27)

  ● balance › consumed › Get the past due consumption balances with all known peers

    expect(received).toEqual(expected) // deep equality

    Expected: ArrayContaining [ObjectContaining {"balance": Any<BigInt>, "peer": Any<String>}]
    Received: []

      44 |       const response = await balance.getPastDueConsumptionBalances(beeDebugUrl())
      45 |
    > 46 |       expect(response.balances).toEqual(
         |                                 ^
      47 |         expect.arrayContaining([
      48 |           expect.objectContaining({
      49 |             peer: expect.any(String),

      at Object.<anonymous> (test/integration/modules/debug/balance.spec.ts:46:33)

  ● balance › consumed › Get the past due consumption balance with a specific peer

    Not Found

      104 |   } catch (e) {
      105 |     if (e.response) {
    > 106 |       throw new BeeResponseError(e.response.status, e.response.statusText)
          |             ^
      107 |     } else if (e.request) {
      108 |       throw new BeeRequestError(e.message)
      109 |     } else {
```

**Comment by AuHau** [comment]
This was on `0.6.0`? I believe that it was an Bee issue and it is resolved as I have not seen this problem recently. Can you verify please?

**Comment by AuHau** [comment]
I think this is resolved so closing this, feel free to reopen if you think it persists.
