### ISSUE TITLE
`addCidConversionFunction` seems to break encrypted uploads

### ISSUE THREAD

**Issue by Cafe137** [ethersphere/bee-js#730]
```
npm i @ethersphere/bee-js
```

```
const STAMP = '...'
const bee = new Bee('http://localhost:1633')
bee.uploadFile(STAMP, 'util.js', 'util.js', { encrypt: true })
```

```
TypeError: Reference does not have expected length 64 characters. Encrypted references are not supported.
```

**Comment by AuHau** [comment]
Hmm yeah, Swarm's CIDs are not supported for encrypted references as they are too long to encode. I guess you are automatically calling the `.cid` property on the uploaded result? If so then you have to remove that on encrypted uploads...

**Comment by Cafe137** [comment]
It seems to run automatically:

```
TypeError: Reference does not have expected length 64 characters. Encrypted references are not supported.
    at assertReference (/Users/aron/Code/swarm-cli/dist/index.js:16490:11)
    at _encodeReference (/Users/aron/Code/swarm-cli/dist/index.js:16415:3)
    at encodeReference (/Users/aron/Code/swarm-cli/dist/index.js:16325:14)
    at Object.get cid [as cid] (/Users/aron/Code/swarm-cli/dist/index.js:108736:46)
    at Function.assign (<anonymous>)
    at addCidConversionFunction (/Users/aron/Code/swarm-cli/dist/index.js:108734:17)
    at Bee.<anonymous> (/Users/aron/Code/swarm-cli/dist/index.js:101538:52)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/aron/Code/swarm-cli/dist/index.js:101250:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by bee-worker** [comment]
Release [v5.0.0](https://github.com/ethersphere/bee-js/releases/tag/v5.0.0) addresses this.
