### ISSUE TITLE
Cannot import Utils

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee-js#759]
I am trying to import `Utils` so that I can use the hex conversion functions. I get the following error with Node 16:
```
/Users/attila/Projects/swarm-pubsub/node_modules/ts-node/src/index.ts:293
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/index.ts:6:15 - error TS2305: Module '"../../../../../Users/attila/Projects/swarm-pubsub/node_modules/@ethersphere/bee-js/dist/types"' has no exported member 'Utils'.

6 import { Bee, Utils } from '@ethersphere/bee-js'
                ~~~~~

    at createTSError (/Users/attila/Projects/swarm-pubsub/node_modules/ts-node/src/index.ts:293:12)
    at reportTSError (/Users/attila/Projects/swarm-pubsub/node_modules/ts-node/src/index.ts:297:19)
    at getOutput (/Users/attila/Projects/swarm-pubsub/node_modules/ts-node/src/index.ts:399:34)
    at Object.compile (/Users/attila/Projects/swarm-pubsub/node_modules/ts-node/src/index.ts:457:32)
    at Module.m._compile (/Users/attila/Projects/swarm-pubsub/node_modules/ts-node/src/index.ts:536:43)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/attila/Projects/swarm-pubsub/node_modules/ts-node/src/index.ts:539:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
```

**Comment by Cafe137** [comment]
Please reopen if you run into this again.

I haven't seen this issue for a long time. I have just tested this with node + CJS as well as ts-node + CJS based on your logs and could not reproduce.
