### ISSUE TITLE
RangeError: Too many properties to enumerate when uploading

### ISSUE THREAD

**Issue by Cafe137** [ethersphere/bee-js#971]
```
RangeError: Too many properties to enumerate
    at Function.keys (<anonymous>)
    at Object.isEmptyObject (/Users/aron/Code/Swarm/swarmwiki/node_modules/axios/lib/utils.js:134:24)
    at getMergedValue (/Users/aron/Code/Swarm/swarmwiki/node_modules/axios/lib/core/mergeConfig.js:21:22)
    at valueFromConfig2 (/Users/aron/Code/Swarm/swarmwiki/node_modules/axios/lib/core/mergeConfig.js:43:14)
    at computeConfigValue (/Users/aron/Code/Swarm/swarmwiki/node_modules/axios/lib/core/mergeConfig.js:98:23)
    at Object.forEach (/Users/aron/Code/Swarm/swarmwiki/node_modules/axios/lib/utils.js:281:10)
    at mergeConfig (/Users/aron/Code/Swarm/swarmwiki/node_modules/axios/lib/core/mergeConfig.js:96:9)
    at Axios.request (/Users/aron/Code/Swarm/swarmwiki/node_modules/axios/lib/core/Axios.js:41:12)
    at wrap (/Users/aron/Code/Swarm/swarmwiki/node_modules/axios/lib/helpers/bind.js:5:15)
    at http (file:///Users/aron/Code/Swarm/swarmwiki/node_modules/@ethersphere/bee-js/dist/mjs/utils/http.js:23:28)
```

**Comment by Cafe137** [comment]
A different variation of this is the following:

```
RangeError: Invalid array length
    at Function.keys (<anonymous>)
    at Object.isEmptyObject (/Users/aron/Code/Swarm/sandbox/node_modules/axios/lib/utils.js:134:24)
    at getMergedValue (/Users/aron/Code/Swarm/sandbox/node_modules/axios/lib/core/mergeConfig.js:21:22)
    at valueFromConfig2 (/Users/aron/Code/Swarm/sandbox/node_modules/axios/lib/core/mergeConfig.js:43:14)
    at computeConfigValue (/Users/aron/Code/Swarm/sandbox/node_modules/axios/lib/core/mergeConfig.js:98:23)
    at Object.forEach (/Users/aron/Code/Swarm/sandbox/node_modules/axios/lib/utils.js:281:10)
    at mergeConfig (/Users/aron/Code/Swarm/sandbox/node_modules/axios/lib/core/mergeConfig.js:96:9)
    at Axios.request (/Users/aron/Code/Swarm/sandbox/node_modules/axios/lib/core/Axios.js:41:12)
    at wrap (/Users/aron/Code/Swarm/sandbox/node_modules/axios/lib/helpers/bind.js:5:15)
    at http (/Users/aron/Code/Swarm/sandbox/node_modules/@ethersphere/bee-js/dist/cjs/utils/http.js:32:52)
```

This is the axios function that triggers it:

```
/**
 * Determine if a value is a empty Object
 *
 * @param {Object} val The value to test
 * @return {boolean} True if value is a empty Object, otherwise false
 */
function isEmptyObject(val) {
  return val && Object.keys(val).length === 0 && Object.getPrototypeOf(val) === Object.prototype;
}
```

This is `val` that gets passed:

```
<Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... 149999950 more bytes>
```

This seems to be an axios bug, in which it tries to determine if a buffer is an object, and calling Object.keys on it kills the JS runtime

**Comment by bee-worker** [comment]
Release [v9.4.1](https://github.com/ethersphere/bee-js/releases/tag/v9.4.1) addresses this.
